# This will need some work: https://travis-ci.org/alienfast/build-control/builds/127275353

sudo: false
git:
  depth: 10

# remove the dist branch and dist tags from travis builds
branches:
  except:
    - dist
    - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/

language: node_js
node_js:
  - "5" # "node" (v6.x) yielded v8::ObjectTemplate::Set() with non-primitive values is deprecated

cache:
  directories:
    - node_modules

before_script:
  - git config --global user.email "mocha-test@alienfast.com"
  - git config --global user.name "Mocha Test"
  - npm install -g gulpjs/gulp-cli#4.0

script: gulp
